"$schema" = "schemas/schema.json"

[default]
description = "Default permissions for the prayer service plugin"
permissions = [
    "allow-start-service",
    "allow-stop-service",
    "allow-update-prayer-times",
    "allow-is-service-running",
]
